<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__horas</name>
   <tag></tag>
   <elementGuidId>2f9e0bf5-5209-4a66-8031-43694b995a16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;horas&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='horas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e41fdda8-94be-4605-823a-8839f91e9575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>43c8ad12-f8b0-4808-a6aa-63da41b7aa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>459abb83-4ab1-4a05-9f01-00b2182e50a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b64cefd6-8a27-4de0-9080-66f8556a0ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d*(\.\d{0,2})?$</value>
      <webElementGuid>ee199a5f-87b9-4f48-a366-8c83617ac87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1.00</value>
      <webElementGuid>13042beb-e9be-4b04-b2d4-6ce8a8a49d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>horas</value>
      <webElementGuid>126e3b4d-2fad-423e-89ad-30b0714eb024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>nb</value>
      <webElementGuid>95df5474-ae9d-49c8-ad2a-9e98b5b498c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-l-0 m-l-0 form-control</value>
      <webElementGuid>5404425c-4436-469d-8e7c-a5c98b060f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crearTiempoForm&quot;)/div[@class=&quot;modal-dialog fix-modal-height&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body fix-modal-hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;p-l-0 m-l-0 form-control&quot;]</value>
      <webElementGuid>e74b33ae-85e4-4be5-89ee-460ac00324be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='horas']</value>
      <webElementGuid>320c8cf2-2979-4dae-9a52-603eaadad4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crearTiempoForm']/div/div/div[2]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>a5237fa9-685a-4521-b396-4c90efe13043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>60a25727-47b8-4cd1-bea5-3cd1f70ad537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '1.00' and @name = 'horas']</value>
      <webElementGuid>a93cd1d2-e928-4179-a409-9538ba7d6c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
