<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__proyecto</name>
   <tag></tag>
   <elementGuidId>1a0da70a-c640-4cc5-a06c-32054f3b1b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proyecto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proyecto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef81f415-a593-45ea-b35f-6ad3817ec48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proyecto</value>
      <webElementGuid>3cbfe2f7-9255-4fd6-b2d7-f219409e3bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72e2b190-02a2-4168-9628-511d9486d384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>131916fc-6552-4e93-bf70-7f0466f184a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>8a529965-9c54-4089-b3d1-97ec3e08e581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c3eeffd-964f-42d3-845d-1d340e12a75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect__input</value>
      <webElementGuid>0ef9d8d8-f843-4346-be2a-abd2e7b781a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proyecto&quot;)</value>
      <webElementGuid>a521f250-a7c5-4c5d-b2a7-3254023c9f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proyecto']</value>
      <webElementGuid>95960866-22a6-434c-99e7-c529f1196c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crearTiempoForm']/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>ff1e4103-0a82-4bb7-ba6f-7de3523d1e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>e5af3d22-16b4-4593-9a35-40c03b82b4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proyecto' and @type = 'text' and @placeholder = 'Seleccionar']</value>
      <webElementGuid>03f2ad53-4fdd-42fa-959b-6faf8b54577c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
