<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__descripcionProyecto</name>
   <tag></tag>
   <elementGuidId>d785e9a8-a82c-46d6-bea9-3ef39770cd24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;descripcionProyecto&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='descripcionProyecto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>48bf3571-e102-40d9-b194-1b67b8e7bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8fe54e25-51aa-4d3b-a36b-c6ba2f03c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descripcionProyecto</value>
      <webElementGuid>e0094f09-4784-46c3-830f-34a8f17aaa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especifica brevemente tu actividad. Ej.: Diseñar arquitectura de seguridad</value>
      <webElementGuid>2026d99c-2d09-457e-a4c1-94d3f9f4d7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crearTiempoForm&quot;)/div[@class=&quot;modal-dialog fix-modal-height&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body fix-modal-hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-12&quot;]/div[@class=&quot;form-group&quot;]/textarea[1]</value>
      <webElementGuid>197b489f-2f5e-42e7-98a6-db6c2e3da647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='descripcionProyecto']</value>
      <webElementGuid>3166e6ee-2454-4c2e-ad5c-62ce34d4543c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crearTiempoForm']/div/div/div[2]/div[4]/div/div/textarea</value>
      <webElementGuid>b3dbf789-232f-4c28-935f-92f1eb1e8626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b32218e0-1956-4f02-bd02-f8b45422b973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'descripcionProyecto' and @placeholder = 'Especifica brevemente tu actividad. Ej.: Diseñar arquitectura de seguridad']</value>
      <webElementGuid>b60158c5-9957-4bb8-b43c-a07a4facf6aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
