<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lyntia_08339_AGILE_2024  Enero traspaso proyecto Inetum</name>
   <tag></tag>
   <elementGuidId>aa962ce0-3d5b-41c5-aa5a-f17a084a666d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12.col-md-12 > div.form-group > div.select-container > div.multiselect > div.multiselect__tags</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='crearTiempoForm']/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcb84145-f751-4aa0-b3e0-376b1a5089b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect__tags</value>
      <webElementGuid>8a360ff4-bd94-45bb-88df-a8a48827c9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Lyntia_08339_AGILE_2024 | Enero traspaso proyecto Inetum </value>
      <webElementGuid>da2e9b86-4eb5-449c-8d48-69e2ca1a27f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crearTiempoForm&quot;)/div[@class=&quot;modal-dialog fix-modal-height&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body fix-modal-hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;select-container&quot;]/div[@class=&quot;multiselect&quot;]/div[@class=&quot;multiselect__tags&quot;]</value>
      <webElementGuid>103b9d89-39e0-4e98-acfe-664cea6754bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='crearTiempoForm']/div/div/div[2]/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>1010e96a-5f52-4dcc-9143-8d74ecd7ba27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[4]</value>
      <webElementGuid>fe534ecf-9834-4e0e-b18d-7640536a192e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES_CONS-S_29732_KIRO GRIFOLS_CONS-S_ATLASSIAN BOLSA HRS._CONS'])[2]/preceding::div[3]</value>
      <webElementGuid>42ea6478-c0ed-412c-98c6-3b5df0315e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>a2ec8e37-cc3f-4703-8e72-f1962da0b770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '    Lyntia_08339_AGILE_2024 | Enero traspaso proyecto Inetum ' or . = '    Lyntia_08339_AGILE_2024 | Enero traspaso proyecto Inetum ')]</value>
      <webElementGuid>4315552b-acf8-4ca8-b0fe-e5e645db4856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
